export type grade = {
  total: number;
  huruf: string;
  nomor: string;
  namemahasiswa: string;
  nim: string;
  nilai_kehadiran: number;
  nilai_keaktifan: number;
  nilai_uts: number;
  nilai_tugas: number;
  nilai_uas: number;
};

export const dataGrade: grade[] = [
  {
    nomor: "1",
    namemahasiswa: "Ahmad Eko",
    nim: "D11111111",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "2",
    namemahasiswa: "Budi Santoso",
    nim: "D11111112",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "3",
    namemahasiswa: "Citra Wijaya",
    nim: "D11111113",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "4",
    namemahasiswa: "Dewi Sari",
    nim: "D11111114",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "5",
    namemahasiswa: "Eka Putra",
    nim: "D11111115",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "6",
    namemahasiswa: "Fauzi Rahman",
    nim: "D11111116",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "7",
    namemahasiswa: "Gita Wulandari",
    nim: "D11111117",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "8",
    namemahasiswa: "Hadi Sutomo",
    nim: "D11111118",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "9",
    namemahasiswa: "Ira Setiawan",
    nim: "D11111119",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "10",
    namemahasiswa: "Joko Susilo",
    nim: "D11111120",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "11",
    namemahasiswa: "Kartika Sari",
    nim: "D11111121",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "12",
    namemahasiswa: "Lia Ramadhani",
    nim: "D11111122",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "13",
    namemahasiswa: "Maulana Malik",
    nim: "D11111123",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "14",
    namemahasiswa: "Nadia Putri",
    nim: "D11111124",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "15",
    namemahasiswa: "Oscar Nugroho",
    nim: "D11111125",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "16",
    namemahasiswa: "Putri Ayu",
    nim: "D11111126",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "17",
    namemahasiswa: "Qori Hidayat",
    nim: "D11111127",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "18",
    namemahasiswa: "Rizky Pratama",
    nim: "D11111128",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "19",
    namemahasiswa: "Siti Aminah",
    nim: "D11111129",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "20",
    namemahasiswa: "Taufik Hidayat",
    nim: "D11111130",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "21",
    namemahasiswa: "Umi Kusuma",
    nim: "D11111131",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "22",
    namemahasiswa: "Vino Wijaya",
    nim: "D11111132",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "23",
    namemahasiswa: "Wahyu Setiawan",
    nim: "D11111133",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "24",
    namemahasiswa: "Xena Putri",
    nim: "D11111134",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "25",
    namemahasiswa: "Yogi Pratama",
    nim: "D11111135",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "26",
    namemahasiswa: "Zara Salsabila",
    nim: "D11111136",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "27",
    namemahasiswa: "Adi Kusuma",
    nim: "D11111137",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "28",
    namemahasiswa: "Bayu Pratama",
    nim: "D11111138",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "29",
    namemahasiswa: "Cindy Wijaya",
    nim: "D11111139",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "30",
    namemahasiswa: "Dian Pratiwi",
    nim: "D11111140",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "31",
    namemahasiswa: "Eko Wahyudi",
    nim: "D11111141",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "32",
    namemahasiswa: "Fira Aulia",
    nim: "D11111142",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "33",
    namemahasiswa: "Gilang Santosa",
    nim: "D11111143",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
  {
    nomor: "34",
    namemahasiswa: "Hendra Pratama",
    nim: "D11111144",
    nilai_kehadiran: 0,
    nilai_keaktifan: 0,
    nilai_uts: 0,
    nilai_tugas: 0,
    nilai_uas: 0,
    total: 0,
    huruf: "E",
  },
];

